aa <- c('ETH_CD_AN_FL',
        'ETH_CD_BG_FL',
        'ETH_CD_CM_FL',
        'ETH_CD_CH_FL',
        'ETH_CD_PI_FL',
        'ETH_CD_HM_FL',
        'ETH_CD_ID_FL',
        'ETH_CD_JA_FL',
        'ETH_CD_KO_FL',
        'ETH_CD_LO_FL',
        'ETH_CD_ML_FL',
        'ETH_CD_TH_FL',
        'ETH_CD_PK_FL',
        'ETH_CD_SL_FL',
        'ETH_CD_TW_FL',
        'ETH_CD_TI_FL',
        'ETH_CD_VI_FL')

nhpi <- c('ETH_CD_FI_FL',
          'ETH_CD_GC_FL',
          'ETH_CD_HW_FL',
          'ETH_CD_OP_FL',
          'ETH_CD_SA_FL',
          'ETH_CD_TO_FL')

white <- c('ETH_CD_WH_FL',
           'ETH_CD_WO_FL')

anna <- c('ETH_CD_AI_FL')

latinx <- c('ETH_CD_LT_FL',
            'ETH_CD_PR_FL',
            'ETH_CD_CU_FL',
            'ETH_CD_MA_FL',
            'ETH_CD_LA_FL')

black <- c('ETH_CD_BL_FL',
           'ETH_CD_AF_FL',
           'ETH_CD_CB_FL',
           'ETH_CD_OA_FL')

swana <- c('ETH_CD_AG_FL',
           'ETH_CD_AR_FL',
           'ETH_CD_AY_FL',
           'ETH_CD_AZ_FL',
           'ETH_CD_BR_FL',
           'ETH_CD_CC_FL',
           'ETH_CD_EM_FL',
           'ETH_CD_GG_FL',
           'ETH_CD_IR_FL',
           'ETH_CD_IQ_FL',
           'ETH_CD_IS_FL',
           'ETH_CD_JD_FL',
           'ETH_CD_KD_FL',
           'ETH_CD_KW_FL',
           'ETH_CD_LE_FL',
           'ETH_CD_OM_FL',
           'ETH_CD_PS_FL',
           'ETH_CD_QT_FL',
           'ETH_CD_SU_FL',
           'ETH_CD_SY_FL',
           'ETH_CD_TK_FL',
           'ETH_CD_YM_FL',
           'ETH_CD_SO_FL',
           'ETH_CD_AL_FL',
           'ETH_CD_BB_FL',
           'ETH_CD_DB_FL',
           'ETH_CD_EG_FL',
           'ETH_CD_LI_FL',
           'ETH_CD_MU_FL',
           'ETH_CD_MO_FL',
           'ETH_CD_SM_FL',
           'ETH_CD_SD_FL',
           'ETH_CD_TS_FL',
           'ETH_CD_NO_FL')
